"use client";

import { Hash, MessageSquareText, RefreshCw, Search, Send, ShieldCheck, UsersRound } from "lucide-react";
import { useRouter } from "next/navigation";
import { useActionState, useDeferredValue, useEffect, useMemo, useRef, useState, useTransition } from "react";
import { markChatChannelReadAction, sendChatMessageAction, type ChatMutationState } from "@/app/(workspace)/chat/actions";
import { CreateChatGroupButton } from "@/components/chat/create-chat-group-dialog";
import { Avatar } from "@/components/ui/avatar";
import type { ChatWorkspaceData } from "@/server/chat/types";

const initialState: ChatMutationState = { status: "idle", message: null, fieldErrors: {}, entityId: null };
const timeFormatter = new Intl.DateTimeFormat("ru-RU", { hour: "2-digit", minute: "2-digit", timeZone: "Europe/Moscow" });
const dayFormatter = new Intl.DateTimeFormat("ru-RU", { day: "numeric", month: "long", year: "numeric", timeZone: "Europe/Moscow" });
const shortDateFormatter = new Intl.DateTimeFormat("ru-RU", { day: "2-digit", month: "2-digit", timeZone: "Europe/Moscow" });
const roleLabels = { admin: "Администратор", dispatcher: "Диспетчер", manager: "Менеджер", accountant: "Бухгалтер", master: "Мастер" } as const;

function ChatComposer({ channelId, requestKey }: { channelId: string; requestKey: string }) {
  const [state, formAction, pending] = useActionState(sendChatMessageAction, initialState);
  const formRef = useRef<HTMLFormElement>(null);
  useEffect(() => { if (state.status === "success") formRef.current?.reset(); }, [state.status]);
  return <form ref={formRef} action={formAction} className="border-t border-white/[0.06] bg-[#0c1114]/92 p-3 backdrop-blur-xl sm:p-4">
    <input type="hidden" name="idempotencyKey" value={requestKey} />
    <input type="hidden" name="channelId" value={channelId} />
    <div className="flex items-end gap-2 rounded-[16px] border border-white/[0.08] bg-black/20 p-2 focus-within:border-[var(--accent)]/25"><textarea name="body" required maxLength={4000} rows={2} placeholder="Напишите сообщение…" className="max-h-36 min-h-12 min-w-0 flex-1 resize-y bg-transparent px-2 py-2 text-sm leading-5 text-white outline-none placeholder:text-[#566067]" /><button type="submit" disabled={pending} className="focus-ring grid size-11 shrink-0 place-items-center rounded-[13px] bg-[var(--accent)] text-[#101308] disabled:cursor-not-allowed disabled:opacity-50" aria-label="Отправить сообщение"><Send className="size-4" /></button></div>
    <div className="mt-2 flex items-center justify-between gap-3 px-1"><p className="text-[9px] text-[#59636a]">Enter — новая строка · до 4000 символов</p>{state.status === "error" ? <p role="alert" className="text-right text-[10px] text-[#ef8a8f]">{state.message}</p> : null}</div>
  </form>;
}

function ChannelList({ data, query, onQueryChange, onSelect, pending, canManage, currentMemberId }: { data: ChatWorkspaceData; query: string; onQueryChange: (query: string) => void; onSelect: (id: string) => void; pending: boolean; canManage: boolean; currentMemberId: string }) {
  const deferredQuery = useDeferredValue(query);
  const filtered = useMemo(() => { const normalized = deferredQuery.trim().toLocaleLowerCase("ru"); return data.channels.filter((channel) => !normalized || [channel.name, channel.description ?? "", channel.lastMessage ?? ""].some((value) => value.toLocaleLowerCase("ru").includes(normalized))); }, [data.channels, deferredQuery]);
  return <aside className="flex min-h-0 flex-col border-b border-white/[0.06] bg-[#0d1317]/72 lg:border-b-0 lg:border-r">
    <div className="flex h-[4.5rem] items-center gap-3 border-b border-white/[0.06] px-3.5"><div className="min-w-0 flex-1"><p className="text-xs font-semibold text-white">Каналы</p><p className="mt-1 text-[9px] uppercase tracking-[0.12em] text-[#59636a]">{data.channels.length} рабочих пространств</p></div>{canManage ? <CreateChatGroupButton memberOptions={data.memberOptions} currentMemberId={currentMemberId} compact /> : null}</div>
    <label className="mx-3 mt-3 flex h-10 items-center gap-2 rounded-[12px] border border-white/[0.07] bg-black/15 px-3"><Search className="size-3.5 text-[#667078]" /><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Найти канал" className="min-w-0 flex-1 bg-transparent text-xs text-white outline-none placeholder:text-[#59636a]" /></label>
    <div className="scrollbar-hidden flex gap-2 overflow-x-auto p-3 lg:block lg:flex-1 lg:space-y-1 lg:overflow-y-auto">{filtered.map((channel) => { const active = channel.id === data.activeChannel?.id; return <button type="button" key={channel.id} disabled={pending} onClick={() => onSelect(channel.id)} className={`focus-ring min-w-[15rem] rounded-[13px] p-3 text-left transition-colors lg:min-w-0 lg:w-full ${active ? "bg-[var(--accent)]/[0.08] ring-1 ring-[var(--accent)]/15" : "hover:bg-white/[0.035]"}`}><div className="flex items-center gap-2"><span className={`grid size-7 shrink-0 place-items-center rounded-[9px] ${active ? "bg-[var(--accent)] text-[#111509]" : "bg-white/[0.05] text-[#788188]"}`}>{channel.kind === "general" ? <MessageSquareText className="size-3.5" /> : <Hash className="size-3.5" />}</span><span className={`min-w-0 flex-1 truncate text-xs font-medium ${active ? "text-white" : "text-[#b7beb9]"}`}>{channel.name}</span>{channel.unreadCount ? <span className="grid min-w-5 place-items-center rounded-full bg-[var(--accent)] px-1.5 py-0.5 text-[9px] font-semibold text-[#101308]">{channel.unreadCount > 99 ? "99+" : channel.unreadCount}</span> : null}</div><p className="mt-2 truncate text-[10px] text-[#667078]">{channel.lastAuthor ? `${channel.lastAuthor}: ` : ""}{channel.lastMessage ?? "Сообщений пока нет"}</p><div className="mt-2 flex items-center justify-between text-[9px] text-[#515b61]"><span>{channel.memberCount} уч.</span><span>{channel.lastMessageAt ? shortDateFormatter.format(new Date(channel.lastMessageAt)) : "—"}</span></div></button>; })}{!filtered.length ? <p className="min-w-56 p-4 text-center text-xs text-[#626c72]">Каналы не найдены</p> : null}</div>
  </aside>;
}

export function ChatWorkspace({ data, canWrite, canManage, composerRequestKey }: { data: ChatWorkspaceData; canWrite: boolean; canManage: boolean; composerRequestKey: string }) {
  const router = useRouter();
  const [channelQuery, setChannelQuery] = useState("");
  const [navigationPending, startNavigation] = useTransition();
  const currentMemberId = data.members.find((member) => member.current)?.id ?? data.memberOptions[0]?.id ?? "";
  const activeChannelId = data.activeChannel?.id ?? null;
  useEffect(() => { if (!activeChannelId) return; startNavigation(async () => { try { await markChatChannelReadAction(activeChannelId); } catch { /* The channel may have been removed between render and acknowledgement. */ } }); }, [activeChannelId]);
  function selectChannel(channelId: string) { startNavigation(async () => { try { await markChatChannelReadAction(channelId); } finally { router.push(`/chat?channel=${channelId}`); } }); }
  if (!data.activeChannel) return <section className="surface-panel mt-7 grid min-h-[32rem] place-items-center p-8 text-center"><div><MessageSquareText className="mx-auto size-7 text-[var(--accent)]" /><p className="mt-4 text-sm text-white">Доступных каналов нет</p><p className="mt-2 text-xs text-[#69737a]">Обратитесь к администратору организации.</p></div></section>;
  const activeChannel = data.activeChannel;
  return <section className="surface-panel mt-6 grid min-h-[calc(100dvh-13rem)] overflow-hidden p-0 lg:grid-cols-[18rem_minmax(0,1fr)] 2xl:grid-cols-[20rem_minmax(0,1fr)_18rem]">
    <ChannelList data={data} query={channelQuery} onQueryChange={setChannelQuery} onSelect={selectChannel} pending={navigationPending} canManage={canManage} currentMemberId={currentMemberId} />
    <div className="flex min-h-[34rem] min-w-0 flex-col bg-[radial-gradient(circle_at_50%_0%,rgba(237,244,59,0.025),transparent_34%),#0b1013]">
      <header className="flex min-h-[4.5rem] items-center gap-3 border-b border-white/[0.06] px-3.5 sm:px-5"><span className="grid size-9 shrink-0 place-items-center rounded-[11px] bg-[var(--accent)]/[0.08] text-[var(--accent)]"><Hash className="size-4" /></span><div className="min-w-0 flex-1"><h2 className="truncate text-sm font-semibold text-white">{activeChannel.name}</h2><p className="mt-0.5 truncate text-[10px] text-[#667078]">{activeChannel.description ?? `${activeChannel.memberCount} участников`}</p></div><button type="button" onClick={() => router.refresh()} className="focus-ring grid size-9 place-items-center rounded-[11px] border border-white/[0.07] text-[#727c82] hover:bg-white/[0.04] hover:text-white" aria-label="Обновить сообщения"><RefreshCw className="size-3.5" /></button></header>
      <div className="scrollbar-hidden flex-1 overflow-y-auto px-3 py-5 sm:px-5"><div className="mx-auto max-w-3xl space-y-4">{data.messages.length ? data.messages.map((message, index) => { const previous = data.messages[index - 1]; const showDay = !previous || dayFormatter.format(new Date(previous.createdAt)) !== dayFormatter.format(new Date(message.createdAt)); return <div key={message.id}>{showDay ? <div className="my-5 flex items-center gap-3"><span className="h-px flex-1 bg-white/[0.05]" /><span className="text-[9px] uppercase tracking-[0.12em] text-[#515b61]">{dayFormatter.format(new Date(message.createdAt))}</span><span className="h-px flex-1 bg-white/[0.05]" /></div> : null}<article className={`flex items-end gap-2.5 ${message.mine ? "justify-end" : "justify-start"}`}>{!message.mine ? <Avatar name={message.authorName} size="sm" tone="violet" /> : null}<div className={`max-w-[min(38rem,82%)] ${message.mine ? "text-right" : "text-left"}`}><div className={`mb-1 flex items-center gap-2 ${message.mine ? "justify-end" : "justify-start"}`}><span className="text-[10px] font-medium text-[#aab2ae]">{message.mine ? "Вы" : message.authorName}</span><span className="text-[9px] text-[#515b61]">{timeFormatter.format(new Date(message.createdAt))}</span></div><p className={`whitespace-pre-wrap break-words rounded-[15px] px-3.5 py-2.5 text-left text-sm leading-5 ${message.mine ? "rounded-br-[5px] bg-[var(--accent)] text-[#15180d]" : "rounded-bl-[5px] border border-white/[0.07] bg-[#12191d] text-[#dce1dd]"}`}>{message.body}</p></div>{message.mine ? <Avatar name={message.authorName} size="sm" tone="lime" /> : null}</article></div>; }) : <div className="grid min-h-72 place-items-center text-center"><div><MessageSquareText className="mx-auto size-6 text-[#566067]" /><p className="mt-3 text-sm text-[#a7afab]">Начните разговор</p><p className="mt-1 text-xs text-[#59636a]">История останется доступна участникам группы.</p></div></div>}</div></div>
      {canWrite ? <ChatComposer key={`${activeChannel.id}:${data.messages.at(-1)?.id ?? "empty"}`} channelId={activeChannel.id} requestKey={composerRequestKey} /> : <p className="border-t border-white/[0.06] p-4 text-center text-xs text-[#69737a]">У вас нет права отправлять сообщения.</p>}
    </div>
    <aside className="hidden min-h-0 flex-col border-l border-white/[0.06] bg-[#0d1317]/62 2xl:flex"><div className="flex h-[4.5rem] items-center gap-3 border-b border-white/[0.06] px-4"><UsersRound className="size-4 text-[var(--accent)]" /><div><p className="text-xs font-semibold text-white">Участники</p><p className="mt-1 text-[9px] text-[#59636a]">{data.members.length} человек</p></div></div><div className="scrollbar-hidden flex-1 space-y-1 overflow-y-auto p-3">{data.members.map((member) => <div key={member.id} className="flex items-center gap-3 rounded-[12px] px-2 py-2.5"><Avatar name={member.displayName} size="sm" tone={member.current ? "lime" : "mint"} /><div className="min-w-0 flex-1"><p className="truncate text-xs text-[#d4d9d6]">{member.displayName}{member.current ? " · вы" : ""}</p><p className="mt-0.5 truncate text-[9px] text-[#5f696f]">{roleLabels[member.role]}</p></div>{member.channelRole === "owner" ? <ShieldCheck className="size-3.5 text-[var(--accent)]" aria-label="Владелец группы" /> : null}</div>)}</div><div className="border-t border-white/[0.06] p-4"><p className="text-[9px] leading-4 text-[#515b61]">Сообщения доступны только участникам этого канала. Доступ проверяется сервером.</p></div></aside>
  </section>;
}
