"use client";

import { ArrowLeft, Bot, Download, FileText, Hash, MessageSquareText, Paperclip, RefreshCw, Search, Send, ShieldCheck, UsersRound } from "lucide-react";
import { useRouter } from "next/navigation";
import { useActionState, useDeferredValue, useEffect, useMemo, useRef, useState, useTransition } from "react";
import { markChatChannelReadAction, sendChatMessageAction, type ChatMutationState } from "@/app/(workspace)/chat/actions";
import { CreateChatGroupButton } from "@/components/chat/create-chat-group-dialog";
import { ManageChatMembersButton } from "@/components/chat/manage-chat-members-dialog";
import { Avatar } from "@/components/ui/avatar";
import { matchesSearchText } from "@/lib/search-normalization";
import type { ChatWorkspaceData } from "@/server/chat/types";

const initialState: ChatMutationState = { status: "idle", message: null, fieldErrors: {}, entityId: null };
const timeFormatter = new Intl.DateTimeFormat("ru-RU", { hour: "2-digit", minute: "2-digit", timeZone: "Europe/Moscow" });
const dayFormatter = new Intl.DateTimeFormat("ru-RU", { day: "numeric", month: "long", year: "numeric", timeZone: "Europe/Moscow" });
const shortDateFormatter = new Intl.DateTimeFormat("ru-RU", { day: "2-digit", month: "2-digit", timeZone: "Europe/Moscow" });
const roleLabels = { developer: "Разработчик", admin: "Администратор", dispatcher: "Диспетчер", manager: "Менеджер", accountant: "Бухгалтер", master: "Мастер" } as const;

function ChatComposer({ channelId, requestKey }: { channelId: string; requestKey: string }) {
  const [state, formAction, pending] = useActionState(sendChatMessageAction, initialState);
  const formRef = useRef<HTMLFormElement>(null);
  useEffect(() => { if (state.status === "success") formRef.current?.reset(); }, [state.status]);
  return <form ref={formRef} action={formAction} className="border-t border-[var(--line)] bg-[var(--surface-raised)] p-3 sm:p-4">
    <input type="hidden" name="idempotencyKey" value={requestKey} />
    <input type="hidden" name="channelId" value={channelId} />
    <div className="flex items-center gap-2 rounded-[16px] border border-[var(--line-strong)] bg-[var(--surface-inset)] p-2 transition-colors focus-within:border-[var(--accent)]"><label className="focus-ring grid size-11 shrink-0 cursor-pointer place-items-center rounded-[13px] border border-[var(--line)] text-[var(--muted)] transition-colors hover:bg-[var(--surface-soft)] hover:text-[var(--text)]" aria-label="Прикрепить файл" title="PDF, изображение, DOCX или XLSX до 15 МБ"><Paperclip className="size-4" /><input name="file" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.docx,.xlsx" className="sr-only" /></label><textarea name="body" required maxLength={4000} rows={1} placeholder="Напишите сообщение…" className="max-h-28 min-h-11 min-w-0 flex-1 resize-none bg-transparent px-2 py-3 text-sm leading-5 text-[var(--text)] outline-none placeholder:text-[var(--text-secondary)]" /><button type="submit" disabled={pending} className="focus-ring grid size-11 shrink-0 place-items-center rounded-[13px] bg-[var(--accent)] text-[var(--on-accent)] transition-colors hover:bg-[var(--accent-strong)] active:translate-y-px disabled:cursor-not-allowed disabled:opacity-50" aria-label="Отправить сообщение"><Send className="size-4" /></button></div>
    <div className="mt-2 flex min-w-0 items-center justify-between gap-3 px-1"><p className="min-w-0 truncate text-[9px] text-[var(--muted)]">До 4000 символов · файл до 15 МБ</p>{state.status === "error" ? <p role="alert" className="text-right text-[10px] text-[var(--danger-ink)]">{state.message}</p> : null}</div>
  </form>;
}

function formatAttachmentSize(bytes: number) {
  return bytes < 1024 * 1024 ? `${Math.ceil(bytes / 1024)} КБ` : `${(bytes / 1024 / 1024).toFixed(1)} МБ`;
}

function MessageAttachment({ attachment, mine }: { attachment: NonNullable<ChatWorkspaceData["messages"][number]["attachment"]>; mine: boolean }) {
  return <a href={`/api/v1/chat/attachments/${attachment.id}/download`} className={`focus-ring mt-2 flex min-h-12 items-center gap-3 rounded-[11px] border px-3 ${mine ? "border-[var(--on-accent)]/35 bg-[var(--accent-strong)]/20 text-[var(--on-accent)]" : "border-[var(--line)] bg-[var(--surface-inset)] text-[var(--text-secondary)]"}`}><FileText className="size-4 shrink-0" /><span className="min-w-0 flex-1"><span className="block truncate text-[10px] font-medium">{attachment.filename}</span><span className={`mt-0.5 block text-[9px] ${mine ? "text-[var(--on-accent)]/75" : "text-[var(--muted)]"}`}>{attachment.extension.toUpperCase()} · {formatAttachmentSize(attachment.sizeBytes)}</span></span><Download className="size-3.5 shrink-0" /></a>;
}

function ChannelList({ data, query, onQueryChange, onSelect, pending, canManage, currentMemberId, mobileVisible, forceCompact }: { data: ChatWorkspaceData; query: string; onQueryChange: (query: string) => void; onSelect: (id: string) => void; pending: boolean; canManage: boolean; currentMemberId: string; mobileVisible: boolean; forceCompact: boolean }) {
  const deferredQuery = useDeferredValue(query);
  const filtered = useMemo(() => data.channels.filter((channel) => matchesSearchText(deferredQuery, [channel.name, channel.description, channel.lastMessage])), [data.channels, deferredQuery]);
  return <aside className={`${mobileVisible ? "flex" : "hidden"} min-h-0 min-w-0 flex-col border-b border-[var(--line)] bg-[var(--surface-raised)] ${forceCompact ? "" : "lg:flex lg:border-b-0 lg:border-r"}`}>
    <div className="flex h-[4.5rem] items-center gap-3 border-b border-[var(--line)] px-3.5"><div className="min-w-0 flex-1"><p className="text-xs font-semibold text-[var(--text)]">Каналы</p><p className="mt-1 text-[9px] uppercase tracking-[0.12em] text-[var(--muted)]">{data.channels.length} рабочих пространств</p></div>{canManage ? <CreateChatGroupButton memberOptions={data.memberOptions} currentMemberId={currentMemberId} compact /> : null}</div>
    <label className="mx-3 mt-3 flex h-10 items-center gap-2 rounded-[12px] border border-[var(--line-strong)] bg-[var(--surface-inset)] px-3"><Search className="size-3.5 text-[var(--muted)]" /><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Найти канал" className="min-w-0 flex-1 bg-transparent text-xs text-[var(--text)] outline-none placeholder:text-[var(--text-secondary)]" /></label>
    <div className={`scrollbar-hidden flex gap-2 overflow-x-auto p-3 ${forceCompact ? "" : "lg:block lg:flex-1 lg:space-y-1 lg:overflow-y-auto"}`}>{filtered.map((channel) => { const active = channel.id === data.activeChannel?.id; return <button type="button" key={channel.id} disabled={pending} onClick={() => onSelect(channel.id)} className={`focus-ring min-w-[15rem] rounded-[13px] p-3 text-left transition-colors ${forceCompact ? "" : "lg:min-w-0 lg:w-full"} ${active ? "bg-[var(--accent-soft)] ring-1 ring-[var(--accent)]/35" : "hover:bg-[var(--surface-soft)]"}`}><div className="flex items-center gap-2"><span className={`grid size-7 shrink-0 place-items-center rounded-[9px] ${active ? "bg-[var(--accent)] text-[var(--on-accent)]" : "bg-[var(--surface-inset)] text-[var(--muted)]"}`}>{channel.kind === "general" ? <MessageSquareText className="size-3.5" /> : <Hash className="size-3.5" />}</span><span className={`min-w-0 flex-1 truncate text-xs font-medium ${active ? "text-[var(--accent-ink)]" : "text-[var(--text-secondary)]"}`}>{channel.name}</span>{channel.unreadCount ? <span className="grid min-w-5 place-items-center rounded-full bg-[var(--accent)] px-1.5 py-0.5 text-[9px] font-semibold text-[var(--on-accent)]">{channel.unreadCount > 99 ? "99+" : channel.unreadCount}</span> : null}</div><p className="mt-2 truncate text-[10px] text-[var(--muted)]">{channel.lastAuthor ? `${channel.lastAuthor}: ` : ""}{channel.lastMessage ?? "Сообщений пока нет"}</p><div className="mt-2 flex items-center justify-between text-[9px] text-[var(--muted)]"><span>{channel.memberCount} уч.</span><span>{channel.lastMessageAt ? shortDateFormatter.format(new Date(channel.lastMessageAt)) : "—"}</span></div></button>; })}{!filtered.length ? <p className="min-w-56 p-4 text-center text-xs text-[var(--muted)]">Каналы не найдены</p> : null}</div>
  </aside>;
}

export function ChatWorkspace({ data, canWrite, canManage, composerRequestKey, readOnlyPreview = false }: { data: ChatWorkspaceData; canWrite: boolean; canManage: boolean; composerRequestKey: string; readOnlyPreview?: boolean }) {
  const router = useRouter();
  const [channelQuery, setChannelQuery] = useState("");
  const [mobileView, setMobileView] = useState<"channels" | "conversation">("conversation");
  const [navigationPending, startNavigation] = useTransition();
  const messageListRef = useRef<HTMLDivElement>(null);
  const currentMemberId = data.members.find((member) => member.current)?.id ?? data.memberOptions[0]?.id ?? "";
  const activeChannelId = data.activeChannel?.id ?? null;
  useEffect(() => { if (readOnlyPreview || !activeChannelId) return; startNavigation(async () => { try { await markChatChannelReadAction(activeChannelId); } catch { /* The channel may have been removed between render and acknowledgement. */ } }); }, [activeChannelId, readOnlyPreview]);
  useEffect(() => {
    const messageList = messageListRef.current;
    if (messageList) messageList.scrollTop = messageList.scrollHeight;
  }, [activeChannelId, data.messages]);
  function selectChannel(channelId: string) {
    if (readOnlyPreview) return;
    setMobileView("conversation");
    startNavigation(async () => { try { await markChatChannelReadAction(channelId); } finally { router.push(`/chat?channel=${channelId}`); } });
  }
  if (!data.activeChannel) return <section className="surface-panel mt-7 grid min-h-[32rem] place-items-center p-8 text-center"><div><MessageSquareText className="mx-auto size-7 text-[var(--accent)]" /><p className="mt-4 text-sm text-[var(--text)]">Доступных каналов нет</p><p className="mt-2 text-xs text-[var(--muted)]">Обратитесь к администратору организации.</p></div></section>;
  const activeChannel = data.activeChannel;
  return <section data-testid="chat-workspace" className={`surface-panel mt-4 grid min-h-0 min-w-0 flex-1 grid-cols-[minmax(0,1fr)] grid-rows-[minmax(0,1fr)] overflow-hidden p-0 ${readOnlyPreview ? "" : "lg:grid-cols-[18rem_minmax(0,1fr)] 2xl:grid-cols-[20rem_minmax(0,1fr)_18rem]"}`}>
    <ChannelList data={data} query={channelQuery} onQueryChange={setChannelQuery} onSelect={selectChannel} pending={navigationPending} canManage={canManage} currentMemberId={currentMemberId} mobileVisible={mobileView === "channels"} forceCompact={readOnlyPreview} />
    <div className={`${mobileView === "conversation" ? "flex" : "hidden"} min-h-0 min-w-0 flex-col bg-[var(--surface)] ${readOnlyPreview ? "" : "lg:flex"}`}>
      <header className="flex min-h-[4.5rem] items-center gap-3 border-b border-[var(--line)] bg-[var(--surface-raised)] px-3.5 sm:px-5">{readOnlyPreview ? null : <button type="button" onClick={() => setMobileView("channels")} className="focus-ring grid size-9 shrink-0 place-items-center rounded-[11px] border border-[var(--line)] text-[var(--muted)] transition-colors hover:bg-[var(--surface-soft)] hover:text-[var(--text)] lg:hidden" aria-label="Вернуться к каналам"><ArrowLeft className="size-4" /></button>}<span className="grid size-9 shrink-0 place-items-center rounded-[11px] bg-[var(--accent-soft)] text-[var(--accent-ink)]"><Hash className="size-4" /></span><div className="min-w-0 flex-1"><h2 className="truncate text-sm font-semibold text-[var(--text)]">{activeChannel.name}</h2><p className="mt-0.5 truncate text-[10px] text-[var(--muted)]">{activeChannel.description ?? `${activeChannel.memberCount} участников`}</p></div>{canManage && activeChannel.kind === "group" && !activeChannel.managed ? <ManageChatMembersButton channel={activeChannel} members={data.members} options={data.memberOptions} /> : null}{readOnlyPreview ? <span className="rounded-full bg-[var(--surface-inset)] px-2.5 py-1 text-[9px] text-[var(--muted)]">Просмотр</span> : <button type="button" onClick={() => router.refresh()} className="focus-ring grid size-9 place-items-center rounded-[11px] border border-[var(--line)] text-[var(--muted)] transition-colors hover:bg-[var(--surface-soft)] hover:text-[var(--text)]" aria-label="Обновить сообщения"><RefreshCw className="size-3.5" /></button>}</header>
      <div ref={messageListRef} data-testid="chat-message-list" className="scrollbar-hidden min-h-0 flex-1 overflow-y-auto px-3 py-5 sm:px-5"><div className="mx-auto max-w-3xl space-y-4">{data.messages.length ? data.messages.map((message, index) => {
        const previous = data.messages[index - 1];
        const showDay = !previous || dayFormatter.format(new Date(previous.createdAt)) !== dayFormatter.format(new Date(message.createdAt));
        return <div key={message.id}>{showDay ? <div className="my-5 flex items-center gap-3"><span className="h-px flex-1 bg-[var(--line)]" /><span className="text-[9px] uppercase tracking-[0.12em] text-[var(--muted)]">{dayFormatter.format(new Date(message.createdAt))}</span><span className="h-px flex-1 bg-[var(--line)]" /></div> : null}{message.kind === "system" ? <article className="mx-auto flex max-w-xl items-start gap-3 rounded-[14px] border border-[var(--info-border)]/45 bg-[var(--info-bg)] px-4 py-3"><span className="grid size-8 shrink-0 place-items-center rounded-[10px] bg-[var(--info)]/10 text-[var(--info)]"><Bot className="size-4" /></span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><span className="text-[9px] font-semibold uppercase tracking-[0.12em] text-[var(--info)]">Системное напоминание</span><span className="text-[9px] text-[var(--muted)]">{timeFormatter.format(new Date(message.createdAt))}</span></div><p className="mt-2 whitespace-pre-wrap text-xs leading-5 text-[var(--text-secondary)]">{message.body}</p></div></article> : <article className={`flex items-end gap-2.5 ${message.mine ? "justify-end" : "justify-start"}`}>{!message.mine ? <Avatar name={message.authorName} size="sm" tone="violet" /> : null}<div className={`max-w-[min(38rem,82%)] ${message.mine ? "text-right" : "text-left"}`}><div className={`mb-1 flex items-center gap-2 ${message.mine ? "justify-end" : "justify-start"}`}><span className="text-[10px] font-medium text-[var(--text-secondary)]">{message.mine ? "Вы" : message.authorName}</span><span className="text-[9px] text-[var(--muted)]">{timeFormatter.format(new Date(message.createdAt))}</span></div><div className={`rounded-[15px] px-3.5 py-2.5 text-left ${message.mine ? "rounded-br-[5px] bg-[var(--accent)] text-[var(--on-accent)]" : "rounded-bl-[5px] border border-[var(--line)] bg-[var(--surface-raised)] text-[var(--text-secondary)]"}`}><p className="whitespace-pre-wrap break-words text-sm leading-5">{message.body}</p>{message.attachment ? <MessageAttachment attachment={message.attachment} mine={message.mine} /> : null}</div></div>{message.mine ? <Avatar name={message.authorName} size="sm" tone="lime" /> : null}</article>}</div>;
      }) : <div className="grid min-h-72 place-items-center text-center"><div><MessageSquareText className="mx-auto size-6 text-[var(--muted)]" /><p className="mt-3 text-sm text-[var(--text-secondary)]">Начните разговор</p><p className="mt-1 text-xs text-[var(--muted)]">История останется доступна участникам группы.</p></div></div>}</div></div>
      {canWrite && !readOnlyPreview ? <ChatComposer key={`${activeChannel.id}:${data.messages.at(-1)?.id ?? "empty"}`} channelId={activeChannel.id} requestKey={composerRequestKey} /> : <p className="border-t border-[var(--line)] bg-[var(--surface-raised)] p-4 text-center text-xs text-[var(--muted)]">{readOnlyPreview ? "В предпросмотре отправка сообщений отключена." : "У вас нет права отправлять сообщения."}</p>}
    </div>
    {readOnlyPreview ? null : <aside className="hidden min-h-0 flex-col border-l border-[var(--line)] bg-[var(--surface-raised)] 2xl:flex"><div className="flex h-[4.5rem] items-center gap-3 border-b border-[var(--line)] px-4"><UsersRound className="size-4 text-[var(--support)]" /><div><p className="text-xs font-semibold text-[var(--text)]">Участники</p><p className="mt-1 text-[9px] text-[var(--muted)]">{data.members.length} человек</p></div></div><div className="scrollbar-hidden flex-1 space-y-1 overflow-y-auto p-3">{data.members.map((member) => <div key={member.id} className="flex items-center gap-3 rounded-[12px] px-2 py-2.5 transition-colors hover:bg-[var(--surface-soft)]"><Avatar name={member.displayName} size="sm" tone={member.current ? "lime" : "mint"} /><div className="min-w-0 flex-1"><p className="truncate text-xs text-[var(--text-secondary)]">{member.displayName}{member.current ? " · вы" : ""}</p><p className="mt-0.5 truncate text-[9px] text-[var(--muted)]">{roleLabels[member.role]}</p></div>{member.channelRole === "owner" ? <ShieldCheck className="size-3.5 text-[var(--accent)]" aria-label="Владелец группы" /> : null}</div>)}</div><div className="border-t border-[var(--line)] p-4"><p className="text-[9px] leading-4 text-[var(--muted)]">Сообщения доступны только участникам этого канала. Доступ проверяется сервером.</p></div></aside>}
  </section>;
}
