"use client";

import { Check, Gauge, LoaderCircle, Pencil, Server } from "lucide-react";
import { useActionState, useCallback, useEffect, useState, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { updateWebsiteInfrastructureAction, type WebsiteMutationState } from "@/app/(workspace)/sites/actions";
import { DateInput } from "@/components/ui/date-time-inputs";
import { Dialog } from "@/components/ui/dialog";
import type { WebsiteDetail, WebsiteHealthStatus, WebsiteStatus } from "@/server/sites/types";

const initialState: WebsiteMutationState = { status: "idle", message: null, fieldErrors: {} };
const inputClass = "focus-ring h-11 w-full rounded-[11px] border border-white/[0.08] bg-black/15 px-3 text-xs text-white outline-none placeholder:text-[#566067]";
const statuses: Array<{ value: WebsiteStatus; label: string }> = [{ value: "active", label: "Активен" }, { value: "setup", label: "Настройка" }, { value: "attention", label: "Нужна проверка" }, { value: "disabled", label: "Отключён" }];
const healthStatuses: Array<{ value: WebsiteHealthStatus; label: string; tone: string }> = [{ value: "healthy", label: "В норме", tone: "#b8f7e4" }, { value: "degraded", label: "Есть отклонения", tone: "#efb454" }, { value: "down", label: "Недоступен", tone: "#ef646a" }];

function Field({ label, error, children }: { label: string; error?: string[]; children: ReactNode }) {
  return <label className="grid gap-2 text-[10px] text-[#7b858b]"><span>{label}</span>{children}{error?.[0] ? <span className="text-[#e18a8e]">{error[0]}</span> : null}</label>;
}

function InfrastructureForm({ site, onComplete }: { site: WebsiteDetail; onComplete: () => void }) {
  const [state, action, pending] = useActionState(updateWebsiteInfrastructureAction, initialState);
  const router = useRouter();
  useEffect(() => { if (state.status !== "success") return; router.refresh(); const timeout = window.setTimeout(onComplete, 650); return () => window.clearTimeout(timeout); }, [onComplete, router, state.status]);
  return <form action={action} className="flex flex-1 flex-col"><input type="hidden" name="websiteId" value={site.id} /><input type="hidden" name="expectedVersion" value={site.version} />
    <div className="flex-1 space-y-7 p-5 sm:p-7">
      <fieldset><legend className="text-[10px] font-semibold uppercase tracking-[0.13em] text-[#69737a]">Состояние сайта</legend><div className="mt-3 grid grid-cols-2 gap-2">{statuses.map((status) => <label key={status.value} className="cursor-pointer"><input type="radio" name="status" value={status.value} defaultChecked={site.status === status.value} className="peer sr-only" /><span className="grid min-h-10 place-items-center rounded-[11px] border border-white/[0.07] px-2 text-[10px] text-[#7e888e] peer-checked:border-[var(--accent)]/30 peer-checked:bg-[var(--accent)]/[0.07] peer-checked:text-white">{status.label}</span></label>)}</div></fieldset>
      <section><div className="flex items-center gap-2"><Server className="size-4 text-[#b8f7e4]" /><h3 className="text-xs font-semibold text-white">Хостинг и оплата</h3></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Провайдер *" error={state.fieldErrors.hostingProvider}><input name="hostingProvider" required defaultValue={site.hosting?.provider ?? ""} placeholder="Selectel" className={inputClass} /></Field><Field label="Тариф *" error={state.fieldErrors.planName}><input name="planName" required defaultValue={site.hosting?.planName ?? ""} placeholder="Cloud M" className={inputClass} /></Field><Field label="Регион сервера *" error={state.fieldErrors.serverRegion}><input name="serverRegion" required defaultValue={site.hosting?.serverRegion ?? ""} placeholder="Москва" className={inputClass} /></Field><Field label="Стоимость в месяц, ₽ *" error={state.fieldErrors.monthlyCostMinor}><input name="monthlyCost" required inputMode="decimal" defaultValue={site.hosting ? site.hosting.monthlyCostMinor / 100 : ""} placeholder="4 900" className={inputClass} /></Field><Field label="Следующая оплата *" error={state.fieldErrors.renewalOn}><DateInput name="renewalOn" required defaultValue={site.hosting?.renewalOn ?? ""} /></Field><Field label="SSL действует до *" error={state.fieldErrors.sslExpiresOn}><DateInput name="sslExpiresOn" required defaultValue={site.hosting?.sslExpiresOn ?? ""} /></Field><Field label="Диск, МБ *" error={state.fieldErrors.diskCapacityMb}><input name="diskCapacityMb" required inputMode="numeric" defaultValue={site.hosting?.diskCapacityMb ?? ""} placeholder="102400" className={inputClass} /></Field><Field label="Память, МБ *" error={state.fieldErrors.memoryCapacityMb}><input name="memoryCapacityMb" required inputMode="numeric" defaultValue={site.hosting?.memoryCapacityMb ?? ""} placeholder="8192" className={inputClass} /></Field></div></section>
      <section><div className="flex items-center gap-2"><Gauge className="size-4 text-[#b8f7e4]" /><h3 className="text-xs font-semibold text-white">Текущая проверка</h3></div><fieldset className="mt-4"><legend className="sr-only">Состояние проверки</legend><div className="grid gap-2 sm:grid-cols-3">{healthStatuses.map((status) => <label key={status.value} className="cursor-pointer"><input type="radio" name="healthStatus" value={status.value} defaultChecked={(site.health?.healthStatus ?? "healthy") === status.value} className="peer sr-only" /><span className="flex min-h-10 items-center justify-center gap-2 rounded-[11px] border border-white/[0.07] px-2 text-[10px] text-[#7e888e] peer-checked:bg-white/[0.04] peer-checked:text-white"><span className="size-2 rounded-full" style={{ backgroundColor: status.tone }} />{status.label}</span></label>)}</div></fieldset><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Доступность, % *" error={state.fieldErrors.uptimePercent}><input name="uptimePercent" required inputMode="decimal" defaultValue={site.health?.uptimePercent ?? "99.9"} className={inputClass} /></Field><Field label="Ответ сервера, мс *" error={state.fieldErrors.responseTimeMs}><input name="responseTimeMs" required inputMode="numeric" defaultValue={site.health?.responseTimeMs ?? "0"} className={inputClass} /></Field><Field label="Нагрузка CPU, % *" error={state.fieldErrors.cpuLoadPercent}><input name="cpuLoadPercent" required inputMode="decimal" defaultValue={site.health?.cpuLoadPercent ?? "0"} className={inputClass} /></Field><Field label="Память использовано, МБ *" error={state.fieldErrors.memoryUsedMb}><input name="memoryUsedMb" required inputMode="numeric" defaultValue={site.health?.memoryUsedMb ?? "0"} className={inputClass} /></Field><Field label="Диск использовано, МБ *" error={state.fieldErrors.diskUsedMb}><input name="diskUsedMb" required inputMode="numeric" defaultValue={site.health?.diskUsedMb ?? "0"} className={inputClass} /></Field></div></section>
      <Field label="Заметка по инфраструктуре" error={state.fieldErrors.notes}><textarea name="notes" maxLength={4000} defaultValue={site.hosting?.notes ?? ""} placeholder="Доступы хранятся отдельно; здесь — особенности продления и обслуживания" className="focus-ring min-h-24 w-full resize-y rounded-[11px] border border-white/[0.08] bg-black/15 p-3 text-xs leading-5 text-white outline-none placeholder:text-[#566067]" /></Field>
      {state.message ? <p role="status" className={`rounded-[12px] border p-3 text-xs leading-5 ${state.status === "success" ? "border-[#b8f7e4]/20 bg-[#b8f7e4]/[0.05] text-[#8ed7b8]" : "border-[#ef646a]/20 bg-[#ef646a]/[0.05] text-[#d89599]"}`}>{state.status === "success" ? <Check className="mr-2 inline size-4" /> : null}{state.message}</p> : null}
    </div><footer className="sticky bottom-0 flex gap-2 border-t border-white/[0.07] bg-[#25272c]/95 p-4 backdrop-blur-xl sm:px-7"><button type="button" onClick={onComplete} disabled={pending} className="focus-ring h-11 flex-1 rounded-[11px] border border-white/[0.08] text-xs text-[#899399]">Отмена</button><button type="submit" disabled={pending || state.status === "success"} className="focus-ring flex h-11 flex-[1.5] items-center justify-center gap-2 rounded-[11px] bg-[var(--accent)] text-xs font-semibold text-[#25272c] disabled:opacity-60">{pending ? <><LoaderCircle className="size-4 animate-spin" />Сохраняем…</> : "Сохранить данные"}</button></footer>
  </form>;
}

export function SiteInfrastructureDialog({ site, canWrite }: { site: WebsiteDetail; canWrite: boolean }) {
  const [open, setOpen] = useState(false);
  const close = useCallback(() => setOpen(false), []);
  if (!canWrite) return null;
  return <><button type="button" onClick={() => setOpen(true)} className="focus-ring flex h-11 items-center gap-2 rounded-[13px] bg-[var(--accent)] px-4 text-sm font-semibold text-[#25272c]"><Pencil className="size-4" />{site.hosting ? "Обновить данные" : "Настроить инфраструктуру"}</button><Dialog open={open} onClose={close} title="Инфраструктура сайта" description="Оплата, ёмкость и текущая проверка сохраняются с историей.">{open ? <InfrastructureForm site={site} onComplete={close} /> : null}</Dialog></>;
}
