"use client";

import { ChartNoAxesCombined, CircleCheck, DatabaseZap, Globe2, Link2, RotateCcw, Search, SlidersHorizontal, UsersRound } from "lucide-react";
import { useCallback, useMemo, useState } from "react";
import { TrendChart } from "@/components/analytics/trend-chart";
import { ConfigureIntegrationDialog, CreateWebsiteButton, type WebsiteIntegrationSelection } from "@/components/sites/site-dialogs";
import { providerLabels, SiteCard } from "@/components/sites/site-card";
import { TrafficSourcesChart } from "@/components/sites/traffic-sources-chart";
import { Dialog } from "@/components/ui/dialog";
import { PageHeading } from "@/components/ui/page-heading";
import { formatMoneyMinor } from "@/lib/format";
import { clientCrypto as crypto } from "@/lib/client-id";
import { websiteProviders, type WebsiteIntegrationStatus, type WebsiteListItem, type WebsiteProvider, type WebsiteSnapshot, type WebsiteStatus } from "@/server/sites/types";

type Filter = "all" | WebsiteStatus;
const filterOptions: Array<{ value: Filter; label: string }> = [{ value: "all", label: "Все сайты" }, { value: "active", label: "Активные" }, { value: "setup", label: "Настройка" }, { value: "attention", label: "Требуют внимания" }, { value: "disabled", label: "Отключённые" }];
const integerFormatter = new Intl.NumberFormat("ru-RU");
type IntegrationFilter = "all" | "none" | WebsiteIntegrationStatus;
type SiteSort = "visitors-desc" | "leads-desc" | "conversion-desc" | "name";
type SiteFilters = { provider: "all" | WebsiteProvider; integration: IntegrationFilter; minLeads: string; sort: SiteSort };
const defaultFilters: SiteFilters = { provider: "all", integration: "all", minLeads: "", sort: "visitors-desc" };

function SignalMetric({ label, value, note, tone }: { label: string; value: string; note: string; tone: string }) {
  return <div className="min-w-0 border-t border-white/[0.06] pt-4 sm:border-l sm:border-t-0 sm:pl-5 sm:pt-0"><span className="text-[9px] uppercase tracking-[0.12em] text-[#69747a]">{label}</span><strong className="mt-2 block truncate font-display text-xl font-semibold tracking-[-0.04em]" style={{ color: tone }}>{value}</strong><span className="mt-1 block truncate text-[9px] text-[#5d676d]">{note}</span></div>;
}

function FilterChoice<T extends string>({ value, current, label, onChange }: { value: T; current: T; label: string; onChange: (value: T) => void }) {
  const selected = value === current;
  return <button type="button" role="radio" aria-checked={selected} onClick={() => onChange(value)} className={`focus-ring min-h-10 rounded-[11px] border px-3 text-left text-xs transition-colors ${selected ? "border-[var(--accent)]/30 bg-[var(--accent)]/[0.08] text-white" : "border-white/[0.07] text-[#858f94] hover:bg-white/[0.035] hover:text-white"}`}>{label}</button>;
}

export function SitesWorkspace({ snapshot, canWrite, preview }: { snapshot: WebsiteSnapshot; canWrite: boolean; preview: boolean }) {
  const [filter, setFilter] = useState<Filter>("all");
  const [query, setQuery] = useState("");
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [filters, setFilters] = useState(defaultFilters);
  const [draftFilters, setDraftFilters] = useState(defaultFilters);
  const [filterError, setFilterError] = useState<string | null>(null);
  const [integrationSelection, setIntegrationSelection] = useState<WebsiteIntegrationSelection | null>(null);
  const openIntegrationDialog = useCallback((site: WebsiteListItem) => setIntegrationSelection({ site, requestKey: crypto.randomUUID() }), []);
  const closeIntegrationDialog = useCallback(() => setIntegrationSelection(null), []);
  const sites = useMemo(() => {
    const normalized = query.trim().toLocaleLowerCase("ru-RU");
    const minimumLeads = filters.minLeads ? Number(filters.minLeads) : null;
    const visible = snapshot.sites.filter((site) => {
      if (filter !== "all" && site.status !== filter) return false;
      if (filters.provider !== "all" && !site.integrations.some((integration) => integration.provider === filters.provider)) return false;
      if (filters.integration === "none" && site.integrations.length) return false;
      if (filters.integration !== "all" && filters.integration !== "none" && !site.integrations.some((integration) => integration.status === filters.integration)) return false;
      if (minimumLeads !== null && site.leads < minimumLeads) return false;
      return !normalized || `${site.name} ${site.domain}`.toLocaleLowerCase("ru-RU").includes(normalized);
    });
    return visible.toSorted((left, right) => {
      if (filters.sort === "leads-desc") return right.leads - left.leads;
      if (filters.sort === "conversion-desc") return right.conversionPercent - left.conversionPercent;
      if (filters.sort === "name") return left.name.localeCompare(right.name, "ru");
      return right.visitors - left.visitors;
    });
  }, [filter, filters, query, snapshot.sites]);
  const activeFilterCount = [filters.provider !== "all", filters.integration !== "all", Boolean(filters.minLeads), filters.sort !== "visitors-desc"].filter(Boolean).length;
  function resetFilters() { setFilter("all"); setQuery(""); setFilters(defaultFilters); setDraftFilters(defaultFilters); setFilterError(null); }
  function applyFilters() {
    if (draftFilters.minLeads && (!/^\d+$/.test(draftFilters.minLeads) || Number(draftFilters.minLeads) > 1_000_000)) { setFilterError("Минимум заявок должен быть целым числом от 0 до 1 000 000."); return; }
    setFilters(draftFilters); setFiltersOpen(false);
  }
  return <div><PageHeading eyebrow="Единый центр сайтов" title="Сайты и трафик" description={preview ? "Демонстрация будущей сквозной аналитики. В рабочем режиме показатели читаются из PostgreSQL." : `Реестр доменов, подключения и путь заявок до оплаченных заказов за ${snapshot.period.startDate} — ${snapshot.period.endDate}.`} action={<CreateWebsiteButton canWrite={canWrite} />} />
    <section aria-label="Сводка по сайтам" className="mt-[clamp(1.5rem,1.1rem+0.8vw,2.25rem)] overflow-hidden border border-white/[0.09] bg-[var(--surface)]"><div className="grid gap-px bg-white/[0.09] lg:grid-cols-[minmax(14rem,0.7fr)_minmax(0,1.5fr)]"><div className="flex items-center gap-4 bg-[var(--surface)] p-5 sm:p-6"><Globe2 className="size-6 shrink-0 text-[var(--accent)]" /><div><p className="text-[10px] uppercase tracking-[0.14em] text-[#7e8785]">Портфель доменов</p><p className="mt-1 font-display text-3xl font-semibold tracking-[-0.05em] text-white">{snapshot.summary.totalSites} <span className="text-sm font-normal text-[#8e9795]">сайтов</span></p><p className="mt-1 text-[10px] text-[var(--accent)]">{snapshot.summary.activeSites} работают штатно</p></div></div><div className="grid gap-4 bg-[var(--surface)] p-5 sm:grid-cols-3 sm:p-6"><SignalMetric label="Аудитория" value={integerFormatter.format(snapshot.summary.visitors)} note={`${integerFormatter.format(snapshot.summary.pageviews)} просмотров`} tone="#B8F7E4" /><SignalMetric label="Заявки" value={integerFormatter.format(snapshot.summary.leads)} note={`${snapshot.summary.paidOrders} привели к оплате`} tone="#B8F7E4" /><SignalMetric label="Конверсия" value={`${snapshot.summary.conversionPercent.toLocaleString("ru-RU")}%`} note={formatMoneyMinor(snapshot.summary.paidRevenueMinor)} tone="#B8F7E4" /></div></div></section>
    <div className="mt-4 flex flex-col gap-3 border-b border-white/[0.06] pb-3 xl:flex-row xl:items-center xl:justify-between"><div className="flex min-w-0 gap-1 overflow-x-auto">{filterOptions.map((option) => <button key={option.value} type="button" onClick={() => setFilter(option.value)} className={`focus-ring h-10 shrink-0 rounded-[10px] px-3 text-xs ${filter === option.value ? "bg-[var(--accent)]/[0.08] text-[var(--accent)]" : "text-[#69747a] hover:text-white"}`}>{option.label}</button>)}</div><div className="flex min-w-0 gap-2"><label className="relative block min-w-0 flex-1 xl:w-72 xl:flex-none"><Search className="pointer-events-none absolute left-3 top-3 size-4 text-[#5f6a71]" /><span className="sr-only">Поиск по сайтам</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Название или домен…" className="focus-ring h-10 w-full rounded-[11px] border border-white/[0.07] bg-black/10 pl-9 pr-3 text-xs text-white outline-none placeholder:text-[#566168]" /></label><button type="button" onClick={() => { setDraftFilters(filters); setFilterError(null); setFiltersOpen(true); }} className={`focus-ring flex h-10 shrink-0 items-center gap-2 rounded-[11px] border px-3 text-xs ${activeFilterCount ? "border-[var(--accent)]/25 bg-[var(--accent)]/[0.06] text-white" : "border-white/[0.07] text-[#858f94]"}`}><SlidersHorizontal className="size-4" />Фильтры{activeFilterCount ? <span className="grid min-w-5 place-items-center rounded-full bg-[var(--accent)] px-1.5 py-0.5 text-[9px] font-semibold text-[#101308]">{activeFilterCount}</span> : null}</button>{query.trim() || filter !== "all" || activeFilterCount ? <button type="button" onClick={resetFilters} aria-label="Сбросить фильтры сайтов" className="focus-ring grid size-10 shrink-0 place-items-center rounded-[11px] border border-white/[0.07] text-[#7c858b]"><RotateCcw className="size-3.5" /></button> : null}</div></div>
    {sites.length ? <section aria-label="Подключённые сайты" className="mt-4 grid gap-4 md:grid-cols-2 2xl:grid-cols-4 2xl:gap-5">{sites.map((site, index) => <SiteCard key={site.id} site={site} index={index} onConfigure={openIntegrationDialog} canWrite={canWrite && !preview} />)}</section> : <section className="surface-panel mt-4 grid min-h-56 place-items-center p-8 text-center"><div><DatabaseZap className="mx-auto size-7 text-[#59656c]" /><h2 className="mt-3 text-sm font-medium text-white">{snapshot.sites.length ? "По фильтру ничего не найдено" : "Добавьте первый сайт"}</h2><p className="mt-2 text-[10px] text-[#69747b]">Рабочая аналитика появится после регистрации домена и подключения источника.</p></div></section>}
    <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.65fr)_minmax(18rem,0.75fr)] 2xl:gap-5"><section className="surface-panel min-w-0 p-[clamp(1rem,0.75rem+0.8vw,1.75rem)]"><div className="mb-6 flex items-start justify-between gap-4"><div><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-[var(--accent)]">30 дней · {integerFormatter.format(snapshot.summary.searchClicks)} поисковых кликов</p><h2 className="mt-2 font-display text-[clamp(1rem,0.9rem+0.35vw,1.3rem)] font-semibold text-white">Трафик без двойного счёта</h2></div><ChartNoAxesCombined className="size-5 text-[#657077]" /></div><TrendChart {...snapshot.trafficTrend} scale="per-series" emptyMessage="За период данных о трафике нет" /></section><section className="surface-panel p-[clamp(1rem,0.75rem+0.8vw,1.75rem)]"><div className="mb-4"><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-[var(--accent)]">CRM-лиды</p><h2 className="mt-2 font-display text-[clamp(1rem,0.9rem+0.35vw,1.3rem)] font-semibold text-white">Источники заявок</h2></div><TrafficSourcesChart entries={snapshot.trafficSources} /></section></div>
    <section className="surface-panel mt-4 p-[clamp(1rem,0.75rem+0.8vw,1.75rem)]"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-[var(--accent)]">Интеграции</p><h2 className="mt-2 font-display text-[clamp(1rem,0.9rem+0.35vw,1.3rem)] font-semibold text-white">Источники аналитики</h2><p className="mt-2 max-w-2xl text-xs leading-5 text-[#747e84]">CRM хранит только property ID и ссылку на серверный секрет. Токены не попадают в HTML, Server Action или audit log.</p></div><span className="flex w-fit items-center gap-2 rounded-full border border-white/[0.07] px-3 py-2 text-[10px] text-[#7c868c]"><Link2 className="size-3.5" />OAuth worker — следующий этап</span></div><div className="mt-6 grid gap-px overflow-hidden rounded-[14px] border border-white/[0.06] bg-white/[0.06] md:grid-cols-2 2xl:grid-cols-4">{websiteProviders.map((provider) => { const integrations = snapshot.sites.flatMap((site) => site.integrations).filter((integration) => integration.provider === provider); const connected = integrations.filter((integration) => integration.status === "connected").length; return <article key={provider} className="min-w-0 bg-[#0d1317] p-4"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-lg bg-white/[0.045]"><CircleCheck className={`size-3.5 ${connected ? "text-[#69d3a4]" : "text-[#59636a]"}`} /></span><h3 className="truncate text-xs font-semibold text-white">{providerLabels[provider]}</h3></div><p className="mt-3 min-h-10 text-[10px] leading-5 text-[#707a80]">{provider === "yandex_metrica" || provider === "ga4" ? "Посетители, просмотры, события и цели" : "Клики, показы и поисковая видимость"}</p><span className="mt-4 inline-block rounded-full bg-white/[0.04] px-2 py-1 text-[9px] text-[#707a80]">{integrations.length ? `${integrations.length} настроено · ${connected} активно` : "Не настроено"}</span></article>; })}</div><div className="mt-4 flex items-start gap-3 rounded-xl border border-[#69d3a4]/15 bg-[#69d3a4]/[0.035] p-4"><UsersRound className="mt-0.5 size-4 shrink-0 text-[#69d3a4]" /><p className="text-[11px] leading-5 text-[#8da399]">Сквозная ценность считается по цепочке `сайт → заявка → заказ → оплата`. Посетители выбираются из одного канонического analytics-провайдера на дату, поэтому параллельные GA4 и Метрика не удваивают аудиторию.</p></div></section>
    <Dialog open={filtersOpen} onClose={() => setFiltersOpen(false)} title="Фильтры сайтов" description="Отберите домены по источнику данных, состоянию интеграции и результативности.">
      <div className="space-y-7 p-5 sm:p-7">
        <fieldset><legend className="mb-3 text-[10px] font-semibold uppercase tracking-[0.13em] text-[#69737a]">Источник данных</legend><div className="grid gap-2 sm:grid-cols-2" role="radiogroup"><FilterChoice value="all" current={draftFilters.provider} label="Любой источник" onChange={(provider) => setDraftFilters((current) => ({ ...current, provider }))} />{websiteProviders.map((provider) => <FilterChoice key={provider} value={provider} current={draftFilters.provider} label={providerLabels[provider]} onChange={(selectedProvider) => setDraftFilters((current) => ({ ...current, provider: selectedProvider }))} />)}</div></fieldset>
        <fieldset><legend className="mb-3 text-[10px] font-semibold uppercase tracking-[0.13em] text-[#69737a]">Состояние интеграции</legend><div className="grid gap-2 sm:grid-cols-2" role="radiogroup"><FilterChoice value="all" current={draftFilters.integration} label="Любое состояние" onChange={(integration) => setDraftFilters((current) => ({ ...current, integration }))} /><FilterChoice value="connected" current={draftFilters.integration} label="Подключено" onChange={(integration) => setDraftFilters((current) => ({ ...current, integration }))} /><FilterChoice value="pending" current={draftFilters.integration} label="Ожидает подключения" onChange={(integration) => setDraftFilters((current) => ({ ...current, integration }))} /><FilterChoice value="error" current={draftFilters.integration} label="Ошибка синхронизации" onChange={(integration) => setDraftFilters((current) => ({ ...current, integration }))} /><FilterChoice value="revoked" current={draftFilters.integration} label="Доступ отозван" onChange={(integration) => setDraftFilters((current) => ({ ...current, integration }))} /><FilterChoice value="none" current={draftFilters.integration} label="Без интеграций" onChange={(integration) => setDraftFilters((current) => ({ ...current, integration }))} /></div></fieldset>
        <fieldset><legend className="mb-3 text-[10px] font-semibold uppercase tracking-[0.13em] text-[#69737a]">Результативность</legend><label><span className="mb-2 block text-[10px] text-[#747e84]">Минимум заявок за период</span><input inputMode="numeric" value={draftFilters.minLeads} onChange={(event) => setDraftFilters((current) => ({ ...current, minLeads: event.target.value.replace(/\D/g, "") }))} placeholder="0" className="h-11 w-full rounded-[12px] border border-white/[0.08] bg-black/10 px-3 text-sm text-white outline-none focus:border-[var(--accent)]/45" /></label></fieldset>
        <fieldset><legend className="mb-3 text-[10px] font-semibold uppercase tracking-[0.13em] text-[#69737a]">Сортировка</legend><div className="grid gap-2 sm:grid-cols-2" role="radiogroup"><FilterChoice value="visitors-desc" current={draftFilters.sort} label="Сначала по трафику" onChange={(sort) => setDraftFilters((current) => ({ ...current, sort }))} /><FilterChoice value="leads-desc" current={draftFilters.sort} label="Сначала по заявкам" onChange={(sort) => setDraftFilters((current) => ({ ...current, sort }))} /><FilterChoice value="conversion-desc" current={draftFilters.sort} label="Сначала по конверсии" onChange={(sort) => setDraftFilters((current) => ({ ...current, sort }))} /><FilterChoice value="name" current={draftFilters.sort} label="По названию" onChange={(sort) => setDraftFilters((current) => ({ ...current, sort }))} /></div></fieldset>
        {filterError ? <p role="alert" className="rounded-[12px] border border-[#ef646a]/20 bg-[#ef646a]/[0.055] p-3 text-xs text-[#dc898e]">{filterError}</p> : null}
      </div>
      <footer className="sticky bottom-0 mt-auto grid shrink-0 grid-cols-[auto_minmax(0,1fr)] gap-2 border-t border-white/[0.07] bg-[#0d1317]/95 p-4 backdrop-blur-xl sm:p-5"><button type="button" onClick={() => { setDraftFilters(defaultFilters); setFilterError(null); }} className="focus-ring h-11 rounded-[12px] border border-white/[0.08] px-4 text-xs text-[#899399]"><RotateCcw className="mr-2 inline size-3.5" />Очистить</button><button type="button" onClick={applyFilters} className="focus-ring h-11 rounded-[12px] bg-[var(--accent)] px-4 text-xs font-semibold text-[#101308]">Показать сайты</button></footer>
    </Dialog>
    <ConfigureIntegrationDialog selection={integrationSelection} onClose={closeIntegrationDialog} />
  </div>;
}
