"use client";

import { ChartNoAxesCombined, CircleCheck, DatabaseZap, Link2, Search, UsersRound } from "lucide-react";
import { useCallback, useMemo, useState } from "react";
import { ProgressList } from "@/components/analytics/progress-list";
import { SummaryCard } from "@/components/analytics/summary-card";
import { TrendChart } from "@/components/analytics/trend-chart";
import { ConfigureIntegrationDialog, CreateWebsiteButton, type WebsiteIntegrationSelection } from "@/components/sites/site-dialogs";
import { providerLabels, SiteCard } from "@/components/sites/site-card";
import { PageHeading } from "@/components/ui/page-heading";
import { formatMoneyMinor } from "@/lib/format";
import { clientCrypto as crypto } from "@/lib/client-id";
import { websiteProviders, type WebsiteListItem, type WebsiteSnapshot, type WebsiteStatus } from "@/server/sites/types";

type Filter = "all" | WebsiteStatus;
const filterOptions: Array<{ value: Filter; label: string }> = [{ value: "all", label: "Все сайты" }, { value: "active", label: "Активные" }, { value: "setup", label: "Настройка" }, { value: "attention", label: "Требуют внимания" }, { value: "disabled", label: "Отключённые" }];
const integerFormatter = new Intl.NumberFormat("ru-RU");

export function SitesWorkspace({ snapshot, canWrite, preview }: { snapshot: WebsiteSnapshot; canWrite: boolean; preview: boolean }) {
  const [filter, setFilter] = useState<Filter>("all");
  const [query, setQuery] = useState("");
  const [integrationSelection, setIntegrationSelection] = useState<WebsiteIntegrationSelection | null>(null);
  const openIntegrationDialog = useCallback((site: WebsiteListItem) => setIntegrationSelection({ site, requestKey: crypto.randomUUID() }), []);
  const closeIntegrationDialog = useCallback(() => setIntegrationSelection(null), []);
  const sites = useMemo(() => snapshot.sites.filter((site) => (filter === "all" || site.status === filter) && `${site.name} ${site.domain}`.toLocaleLowerCase("ru-RU").includes(query.trim().toLocaleLowerCase("ru-RU"))), [filter, query, snapshot.sites]);
  return <div><PageHeading eyebrow="Единый центр сайтов" title="Сайты и трафик" description={preview ? "Демонстрация будущей сквозной аналитики. В рабочем режиме показатели читаются из PostgreSQL." : `Реестр доменов, подключения и путь заявок до оплаченных заказов за ${snapshot.period.startDate} — ${snapshot.period.endDate}.`} action={<CreateWebsiteButton canWrite={canWrite} />} />
    <section aria-label="Сводка по сайтам" className="mt-[clamp(1.5rem,1.1rem+0.8vw,2.25rem)] grid gap-3 min-[460px]:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6"><SummaryCard label="Сайтов в контуре" value={String(snapshot.summary.totalSites)} change={`${snapshot.summary.activeSites} активны`} tone="lime" /><SummaryCard label="Посетители" value={integerFormatter.format(snapshot.summary.visitors)} change="канонический источник" tone="mint" /><SummaryCard label="Просмотры" value={integerFormatter.format(snapshot.summary.pageviews)} change="за 30 дней" tone="violet" /><SummaryCard label="Поисковые клики" value={integerFormatter.format(snapshot.summary.searchClicks)} change="Google + Яндекс" tone="mint" /><SummaryCard label="Заявки" value={integerFormatter.format(snapshot.summary.leads)} change={`${snapshot.summary.paidOrders} с оплатой`} tone="violet" /><SummaryCard label="Конверсия в заявку" value={`${snapshot.summary.conversionPercent.toLocaleString("ru-RU")}%`} change={formatMoneyMinor(snapshot.summary.paidRevenueMinor)} tone="amber" /></section>
    <div className="mt-4 flex flex-col gap-3 border-b border-white/[0.06] pb-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex min-w-0 gap-1 overflow-x-auto">{filterOptions.map((option) => <button key={option.value} type="button" onClick={() => setFilter(option.value)} className={`focus-ring h-10 shrink-0 rounded-[10px] px-3 text-xs ${filter === option.value ? "bg-[var(--accent)]/[0.08] text-[var(--accent)]" : "text-[#69747a] hover:text-white"}`}>{option.label}</button>)}</div><label className="relative block w-full lg:w-72"><Search className="pointer-events-none absolute left-3 top-3 size-4 text-[#5f6a71]" /><span className="sr-only">Поиск по сайтам</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Название или домен…" className="focus-ring h-10 w-full rounded-[11px] border border-white/[0.07] bg-black/10 pl-9 pr-3 text-xs text-white outline-none placeholder:text-[#566168]" /></label></div>
    {sites.length ? <section aria-label="Подключённые сайты" className="mt-4 grid gap-4 md:grid-cols-2 2xl:grid-cols-4 2xl:gap-5">{sites.map((site, index) => <SiteCard key={site.id} site={site} index={index} onConfigure={openIntegrationDialog} canWrite={canWrite && !preview} />)}</section> : <section className="surface-panel mt-4 grid min-h-56 place-items-center p-8 text-center"><div><DatabaseZap className="mx-auto size-7 text-[#59656c]" /><h2 className="mt-3 text-sm font-medium text-white">{snapshot.sites.length ? "По фильтру ничего не найдено" : "Добавьте первый сайт"}</h2><p className="mt-2 text-[10px] text-[#69747b]">Рабочая аналитика появится после регистрации домена и подключения источника.</p></div></section>}
    <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.65fr)_minmax(18rem,0.75fr)] 2xl:gap-5"><section className="surface-panel min-w-0 p-[clamp(1rem,0.75rem+0.8vw,1.75rem)]"><div className="mb-6 flex items-start justify-between gap-4"><div><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-[var(--accent)]">30 дней</p><h2 className="mt-2 font-display text-[clamp(1rem,0.9rem+0.35vw,1.3rem)] font-semibold text-white">Трафик без двойного счёта</h2></div><ChartNoAxesCombined className="size-5 text-[#657077]" /></div><TrendChart {...snapshot.trafficTrend} scale="per-series" emptyMessage="За период данных о трафике нет" /></section><section className="surface-panel p-[clamp(1rem,0.75rem+0.8vw,1.75rem)]"><div className="mb-6"><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-[var(--accent)]">CRM-лиды</p><h2 className="mt-2 font-display text-[clamp(1rem,0.9rem+0.35vw,1.3rem)] font-semibold text-white">Источники заявок</h2></div>{snapshot.trafficSources.length ? <ProgressList entries={snapshot.trafficSources} accent="#9c82e8" /> : <div className="grid min-h-56 place-items-center text-center text-[10px] leading-5 text-[#626d74]">UTM-источники появятся после приёма первых заявок.</div>}</section></div>
    <section className="surface-panel mt-4 p-[clamp(1rem,0.75rem+0.8vw,1.75rem)]"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-[var(--accent)]">Интеграции</p><h2 className="mt-2 font-display text-[clamp(1rem,0.9rem+0.35vw,1.3rem)] font-semibold text-white">Источники аналитики</h2><p className="mt-2 max-w-2xl text-xs leading-5 text-[#747e84]">CRM хранит только property ID и ссылку на серверный секрет. Токены не попадают в HTML, Server Action или audit log.</p></div><span className="flex w-fit items-center gap-2 rounded-full border border-white/[0.07] px-3 py-2 text-[10px] text-[#7c868c]"><Link2 className="size-3.5" />OAuth worker — следующий этап</span></div><div className="mt-6 grid gap-px overflow-hidden rounded-[14px] border border-white/[0.06] bg-white/[0.06] md:grid-cols-2 2xl:grid-cols-4">{websiteProviders.map((provider) => { const integrations = snapshot.sites.flatMap((site) => site.integrations).filter((integration) => integration.provider === provider); const connected = integrations.filter((integration) => integration.status === "connected").length; return <article key={provider} className="min-w-0 bg-[#0d1317] p-4"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-lg bg-white/[0.045]"><CircleCheck className={`size-3.5 ${connected ? "text-[#69d3a4]" : "text-[#59636a]"}`} /></span><h3 className="truncate text-xs font-semibold text-white">{providerLabels[provider]}</h3></div><p className="mt-3 min-h-10 text-[10px] leading-5 text-[#707a80]">{provider === "yandex_metrica" || provider === "ga4" ? "Посетители, просмотры, события и цели" : "Клики, показы и поисковая видимость"}</p><span className="mt-4 inline-block rounded-full bg-white/[0.04] px-2 py-1 text-[9px] text-[#707a80]">{integrations.length ? `${integrations.length} настроено · ${connected} активно` : "Не настроено"}</span></article>; })}</div><div className="mt-4 flex items-start gap-3 rounded-xl border border-[#69d3a4]/15 bg-[#69d3a4]/[0.035] p-4"><UsersRound className="mt-0.5 size-4 shrink-0 text-[#69d3a4]" /><p className="text-[11px] leading-5 text-[#8da399]">Сквозная ценность считается по цепочке `сайт → заявка → заказ → оплата`. Посетители выбираются из одного канонического analytics-провайдера на дату, поэтому параллельные GA4 и Метрика не удваивают аудиторию.</p></div></section>
    <ConfigureIntegrationDialog selection={integrationSelection} onClose={closeIntegrationDialog} />
  </div>;
}
